### ISSUE TITLE
[Question] auto_loader.rb

### ISSUE THREAD

**Issue by RyanBram** [ashes999/rpg-maker-resource-index#17]
Hi, Ashiq, (^_^)
Thanks for creating RPG Maker resources repository.
I tried your auto_loader.rb scripts and found it successfully convert my *.rvdata2 scripts into plain text. It is nice to know there is a way to make collaboration easier such as this script. My questions are:
1. Why every script is converted in one line plain text? It is very hard to read even in plain text format. Is it possible for you to improve  auto_loader.rb to generate multiple line plain text?
2. Is there a way to encrypt the format back to *.rvdata2? 

Thanks

**Comment by ashes999** [comment]
Hi!

I think you're mixing two scripts up. `auto_loader.rb` just loads everything in the `Scripts` folder. `expose_data.rb` actually decompiles the `rvdata2` files.

You can see the code [here](https://github.com/ashes999/rpg-maker-resources/blob/gh-pages/vx-ace/scripts/expose_data.rb). Essentially, we're just calling `File.binread` and `Marshall.load`.

What I wanted is a way to collaborate with multiple people. Editing binary files just doesn't work well. Decompiling them to text at least made some changes more visible, but it's really hard to read.

As for your questions:

1) It's probably due to your OS, and/or the way I write the file. It should be easy to fix (probably just need to add `\r`)
2) Yes. You can do the opposite of marshalling. But, notice that I removed some stuff (eg. memory addresses) -- the purpose was just to increase readability. It won't work.

What are you trying to accomplish by re-writing them? Generally, they should be treated as read-only, because they're managed by RPG Maker.

**Comment by RyanBram** [comment]
> 1) It's probably due to your OS, and/or the way I write the file. It should be easy to fix (probably just need to add \r)

Will you add quickfix for it? Or may you tell me how to do it myself?

> 2) Yes. You can do the opposite of marshalling. But, notice that I removed some stuff (eg. memory addresses) -- the purpose was just to increase readability. It won't work

Maybe the script can be exported as normal plain text instead of binary text? It is what Gubid did with [his script](http://www.rpgmakervxace.net/topic/12716-script-importexport/)

> What are you trying to accomplish by re-writing them? Generally, they should be treated as read-only, because they're managed by RPG Maker.

By rewriting them back, I can automatically batch update every change made by version-control system in my team without manually put it back in RPG Maker software.

Sorry for my English.

**Comment by ashes999** [comment]
1) Sure, I can fix it.
2) That script does something different. The goal of that script is to allow you to export scripts that are added in the script editor. My `auto_loader` script gets around that, because you don't even need to put any scripts in the editor other than `auto_loader` itself.

With the `.rvdata` files, what you're asking is not possible. Ruby marshalling isn't meant to be used this way (export, modify, and then re-import maps). Not all of the information is represented fully in the text file that comes out to begin with. Plus, it includes some temporary information, such as memory addresses of objects, which is meaningless when you convert it back (these numbers change when you re-run your game).

What are you trying to accomplish?

**Comment by ashes999** [comment]
This issue is more than a year old. Please re-open it if you have further questions @RyanBram
